version: 2.1

executors:
  jdk-executor:
    docker:
      - image: circleci/openjdk:11-jdk
    working_directory: "~/build"
    environment:

parameters:
  workflow_build_and_deploy:
    type: boolean
    default: true
  workflow_release:
    type: boolean
    default: false
  build_env:
    type: string
    default: dev
  build_version:
    type: string
    default: 1.0.0

jobs:
  build:
    executor: jdk-executor
    environment:
    steps:
      - add_ssh_keys:
          fingerprints:
            - "28:8d:87:e8:f6:6f:1b:c1:44:82:d0:88:a8:9e:d1:ce"
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle.kts" }}
          - v1-dependencies-
      - run:
          name: Downloading Gradle depedencies
          command: gradle dependencies
      - save_cache:
          paths:
          - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle.kts" }}
      - run:
          name: Running Junits Tests
          command: gradle test

  deploy:
    executor: jdk-executor
    steps:
      - add_ssh_keys:
          fingerprints:
            - "28:8d:87:e8:f6:6f:1b:c1:44:82:d0:88:a8:9e:d1:ce"
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle.kts" }}
            - v1-dependencies-
      - run:
          name: Downloading Gradle depedencies
          command: gradle dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle.kts" }}
      - run:
          name: Building Java artifact
          command: gradle scmVersion build
      - run:
          name: Pushing SCM Tags
          command: gradle scmVersionPush

  release:
    executor: jdk-executor
    environment:
      BUILD_ENV: << pipeline.parameters.build_env >>
      BUILD_VERSION: << pipeline.parameters.build_version >>
    steps:
      - add_ssh_keys:
          fingerprints:
            - "28:8d:87:e8:f6:6f:1b:c1:44:82:d0:88:a8:9e:d1:ce"
      - run:
          name: Checkout
          command: |
            echo "checking out version:"
            echo $BUILD_VERSION
      - run:
          name: Execute Terraform
          command: |
            echo "terraform:"
            echo $BUILD_ENV

workflows:
  version: 2.1
  build_and_deploy:
    when: << pipeline.parameters.workflow_build_and_deploy >>
    jobs:
      - build:
          filters:
            branches:
              only: /.*/
      - deploy:
          filters:
            branches:
              only: master
          requires:
            - build
  release:
    when: << pipeline.parameters.workflow_release >>
    jobs:
      - release